server:
  port: 8040
  
spring:
  application:
    name: hystrix-turbine
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-second: 5 #心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10 #发呆时间，即服务续约到期时间（缺省为90s）
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/
    registry-fetch-interval-seconds: 5
    
   
    
#turbine:
#  appConfig: USER-SERVICE,USER-ORDER
#  clusterNameExpression: "'default'"
  
  
  
